### ISSUE TITLE
ir_to_bytecode_syntax's build.rs modifies the src directory

### ISSUE THREAD

**Issue by TristanDebrunner** [solana-labs/libra#20]
`language/compiler/ir_to_bytecode/syntax` won't publish because it's build script currently places the output file in `src/`.

**Comment by TristanDebrunner** [comment]
I can easily make the build script generate into `OUT_DIR`, but I can't find a way to get the `lib.rs` file to link to the new location (currently it just uses `pub mod syntax;`).

**Comment by TristanDebrunner** [comment]
@garious we were talking about similar for protobuf yesterday, any ideas?

**Comment by garious** [comment]
For the short-term, check in that generated code too?
